// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Project numbers (1-based, matching the projects list) that have a
// full-size mockup at /works/{n}.webp. Re-run `npm run images` to refresh.
export const worksWithFullSize: number[] = [2, 3, 4, 5, 6, 8, 9, 10];
