"use client";

import { useState } from "react";
import { ArrowUpRight } from "@phosphor-icons/react";
import { Reveal } from "@/components/reveal";
import { WorkLightbox, type Work } from "@/components/work-lightbox";
import { worksWithFullSize } from "@/content/works";
import type { Dict } from "@/lib/dict";

/**
 * The project grid, plus the full-size viewer it opens.
 *
 * Not every project has a mockup yet — `worksWithFullSize` is generated by the
 * image pipeline from what actually exists in /public/works. Those that do open
 * the lightbox; the rest keep their old behaviour and link out to Behance, so a
 * missing file degrades to the previous experience instead of a dead click.
 */
export function ProjectsGrid({ dict }: { dict: Dict }) {
  const [openWork, setOpenWork] = useState<Work | null>(null);

  return (
    <>
      <div className="mt-10 grid grid-cols-1 gap-x-4 gap-y-8 sm:mt-12 sm:grid-cols-2 sm:gap-y-10">
        {dict.projects.map((p, i) => {
          const n = i + 1;
          const hasFullSize = worksWithFullSize.includes(n);

          const inner = (
            <>
              {/* label bar */}
              <div className="flex items-center justify-between rounded-[16px] bg-paper-pure px-5 py-3.5">
                <p className="text-[15px] font-medium tracking-[-0.4px] text-ink transition-colors duration-300 group-hover:text-accent sm:text-[16px]">
                  {p.name}
                  <span className="text-muted-ink"> /{p.year}</span>
                </p>
                <span className="font-mono text-[10px] uppercase tracking-[2px] text-muted-ink">
                  {p.type}
                </span>
              </div>

              {/* image + gradient + logo */}
              <div className="relative h-[260px] overflow-hidden rounded-[16px] bg-ink/5 sm:h-[340px] lg:h-[390px]">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`/projects/${n}.webp`}
                  alt={p.name}
                  className="h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-[1.06]"
                  loading="lazy"
                />
                <div className="absolute inset-0 bg-gradient-to-b from-[rgba(0,0,0,0.07)] to-[rgba(0,0,0,0.35)]" />
                <div className="absolute inset-0 bg-black/0 transition-colors duration-500 group-hover:bg-black/15" />
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`/projects/logos/${n}.svg`}
                  alt={`${p.name} logo`}
                  className="absolute bottom-[14%] left-1/2 w-[125px] max-w-[40%] -translate-x-1/2 object-contain lg:w-[250px] lg:max-w-[80%]"
                />
                {hasFullSize && (
                  <span
                    aria-hidden
                    className="pointer-events-none absolute right-4 top-4 flex size-10 translate-y-1 items-center justify-center rounded-full bg-white/15 text-white opacity-0 backdrop-blur-md transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100"
                  >
                    <ArrowUpRight weight="bold" className="size-4" />
                  </span>
                )}
              </div>
            </>
          );

          const cls =
            "group flex flex-col gap-2 text-left transition-transform duration-300 ease-out hover:-translate-y-1";

          return (
            <Reveal key={n} delay={(i % 2) * 0.08}>
              {hasFullSize ? (
                <button
                  type="button"
                  onClick={() => setOpenWork({ ...p, n })}
                  className={`${cls} w-full`}
                >
                  {inner}
                </button>
              ) : (
                <a
                  href={dict.contacts.behance.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={cls}
                >
                  {inner}
                </a>
              )}
            </Reveal>
          );
        })}
      </div>

      <WorkLightbox
        work={openWork}
        onClose={() => setOpenWork(null)}
        dict={dict}
      />
    </>
  );
}
